### ISSUE TITLE
Focus problem when multiple kendo-combobox in a form 

### ISSUE THREAD

**Issue by EdCharbeneau** [telerik/kendo-angular2#131]
When you have multiple kendo-combobox components in a form you can only focus on the first combobox. Pressing tab+clicking on the second will sometimes allow focus.

http://plnkr.co/edit/xfSuTqwGXNrLw5K5s5MA?p=preview

**Comment by tapopov** [comment]
Hi @EdCharbeneau, thanks for reporting this. We're looking into it.

**Comment by tapopov** [comment]
Hey @EdCharbeneau, this happens because there are two components nested in a <label> element. The same behavior occurs if two text <input> elements are nested as well. Closing this, as it is not related to the ComboBox itself. 
See [working example](http://plnkr.co/edit/jIr4TGkhI62ZetYx5KbF?p=preview)
