### ISSUE TITLE
Dropdown positioning wrong inside Kendo-Dialog

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular2#140]
Plunkr:

http://plnkr.co/edit/LMHNRoMQst0PiAbFszak?p=preview

**Comment by tapopov** [comment]
Thanks for reporting this @simon11196. We will look into it.

**Comment by ggkrustev** [comment]
Hi @simon11196,
my local tests show that the widget works just fine with the latest official version of `kendo-angular-dropdowns` and `kendo-angular-popup`:

![screen shot 2016-12-19 at 10 49 53 am](https://cloud.githubusercontent.com/assets/495188/21306201/791032e0-c5d8-11e6-826d-fee6ed64ec29.png)

Here is the repro demo:

https://github.com/ggkrustev/ng2-test-demo/tree/ddl-in-dialog

Can you confirm the depicted behavior?

**Comment by egdraper** [comment]
I was having the same problem. I realized that the installation given in the documentation 
`npm install --save @progress/kendo-angular-dropdowns` installs an old version (rather than the newest).  

use `npm view @progress/kendo-angular-dropdowns versions` to check that you have the newest version declared in your package.json file. If not, update it.

Mine was: `^0.16.3`
Changing it to: `^0.20.2` fixed the problem.

**Comment by tsvetomir** [comment]
@egdraper this is normal for the 0.x range - minor versions are considered to potentially contain breaking changes.

For example, the `^0.16.3` range selector will behave as `>=0.16.3<0.17`. Contrast this with `^1.16.3` that will behave as `>=1.16.3<2.0.0`.

Try it out in the [semver calculator](https://semver.npmjs.com/).

**Comment by ggkrustev** [comment]
I will close this issue as resolved then.
