### ISSUE TITLE
Grid "Action Column" with Bootstrap drop-down cropped

### ISSUE THREAD

**Issue by paulstringerdb** [telerik/kendo-angular2#159]
We have a quite extensive set of actions for some of the items in our grids. We plan to add a drop-down action command using the bootstrap "drop-down" component.

Currently this drop down inside a kendo grid cell is hidden behind other grid rows and components. Will there be a mechanism for adding a drop down to a cell that doesn't get cropped?

I know this is likely to be CSS issue, but it would be very useful to have this feature without having to resort to all kinds of JQuery to achieve it.

Any ideas ?...

**Comment by rusev** [comment]
There was a [similar issue](https://github.com/telerik/kendo-angular2/issues/68) reported some time ago, but it should be working properly with latest versions.

Can you provide us a plnkr with the described issue?

**Comment by paulstringerdb** [comment]
Hi,

Please see this [plunk](http://plnkr.co/edit/0GYSlpHanyf7ttimZh4t?p=preview).
It uses BootStrap drop down inside a grid cell.

(Can't get either plunk in the other article to work)

Paul.

**Comment by gyoshev** [comment]
@paulstringerdb the issue is caused by the specific styling of the example. The `my-app` container, the`html` and `body` elements have `overflow:hidden`, so any content that is outside them is cropped out. See [this updated plunkr](http://plnkr.co/edit/A2lVsvAFGdN4Msey7laO?p=preview) for a working demo.

**Comment by paulstringerdb** [comment]
Hi,

Please re-check the plunkr results you created.

The column widths of the data rows do not line up with the column widths of the header when using the styling as suggested. The vertical lines are out of alignment.

if you remove the following css: -

     .k-grid-content,
     .k-grid-content td {
         overflow: visible;
     }

Then the columns widths are lined up, but the bootstrap drop-down is again cropped.

**Comment by paulstringerdb** [comment]
And why do you close issues that are not fixed ?

**Comment by gyoshev** [comment]
@paulstringerdb sorry that I didn't elaborate.

First, let's take a few steps back, to restore the default styling. The issue with cropped-out menus was caused by third-party styling of the `my-app` container. The headers do not align because the styles for `.k-grid-content` removes the scrollbar and breaks the layout. Removing the style overrides makes the headers line up, as you have found out.

Now, to the main issue: the cropped-out popups. The Bootstrap popups use `position: absolute` for alignment. You can either make them overflow the grid container, or make the grid scrollable (either content overflows or it scrolls, can't do both). Therefore, if the grid is non-scrollable, we can set `.k-grid td { overflow: visible }` and drop-downs will be able to pop out of the grid. We cannot remove the default `overflow: hidden` style on the grid cells, because the grid uses `text-overflow: ellipsis` by design (which requires `overflow: hidden`). Thus, the above style is required as long as you want to pop out content from the grid. Thus, we won't be fixing this issue -- if you need to use bootstrap drop-downs in the grid, set `[scrollable]="none"` and add the style `.k-grid td { overflow: visible; }`. The [plunkr snippet](http://plnkr.co/edit/A2lVsvAFGdN4Msey7laO?p=preview) has been updated with this approach.

If you need a scrollable grid with drop-down buttons, we are working on a component that is similar to the bootstrap drop-down, but uses the **kendo-popup** component for drop-downs. Since **kendo-poup** uses  `position: fixed` to align the popup, it will be able to be nested in both scrollable and non-scrollable grids, and will not be trimmed by the grid cells.

**Comment by paulstringerdb** [comment]
So this no longer works... ROFLMAO...

**Comment by ssbhadri** [comment]
If you need a scrollable grid with drop-down buttons, we are working on a component that is similar to the bootstrap drop-down, but uses the kendo-popup component for drop-downs. Since kendo-poup uses position: fixed to align the popup, it will be able to be nested in both scrollable and non-scrollable grids, and will not be trimmed by the grid cells.

@paulstringerdb -  Is this control developed in kendo?
