### ISSUE TITLE
Grid features like Detail Template do not work in local NG-CLI project with local dependencies acquired by npm.

### ISSUE THREAD

**Issue by dbaranau** [telerik/kendo-angular2#167]
Hi guys,

The demo of you components looks amazing and works well in plunker provided at (http://www.telerik.com/kendo-angular-ui/components/).

The problem is Grid and PanelBar components start behaving very strange once I create a local project and use your guidelines from sources like below:
http://www.telerik.com/kendo-angular-ui/getting-started/
http://www.telerik.com/blogs/cooking-with-aspnet-core-and-angular-2
http://www.telerik.com/blogs/using-kendo-ui-with-angular-2

Specifically, Grid Detail Template and other features like Cell Template do not work properly in local project with @progress and @telerik packages squired and stored locally. I used exact steps from provided guidelines and articles. 

Try creating a simple angular CLI project and install your packages using npm, then copy-paste Detail Template example from http://www.telerik.com/kendo-angular-ui/components/grid/#toc-detail-template and you see that there is no expand buttons. I saw other features not working in Grid and PanelBar.

That could be a version difference between what you use in your plunker and what npm gives when I use it in a simple Angular 2 CLI project. Versions of my dependencies:
    "@progress/kendo-angular-buttons": "^0.14.4",
    "@progress/kendo-angular-dialog": "^0.13.3",
    "@progress/kendo-angular-dropdowns": "^0.22.1",
    "@progress/kendo-angular-grid": "^0.10.0",
    "@progress/kendo-angular-layout": "^0.17.0",
    "@progress/kendo-angular-popup": "^0.14.5",
    "@progress/kendo-data-query": "^0.3.4",
    "@telerik/kendo-theme-bootstrap": "^0.10.0",
    "@telerik/kendo-theme-default": "^1.33.4",

Please advise or let me know if you need more details.

Thanks,
Dmitry

**Comment by satlom** [comment]
It works if I downgrade the grid component to 0.9.0.

**Comment by dbaranau** [comment]
Cool, thanks. Could you provide the list of stable versions of other packages like layout so that I can use markup snippets from your plunkers in demo locally in my my project? You should have a list of versions of the packages you used for your plunkers.

**Comment by rkonstantinov** [comment]
Actually, as the packages are not 1.0.0 version, technically there are no "stable" versions.

Regarding the issues mentioned.  

- The expand/collapse buttons are missing due to the fact that Grid package now depends on the version 2.0.0 of the theme package. Which is now located on the Progress NPM registry and is scope with @progress instead @telerik as previously. Please check [this](http://www.telerik.com/kendo-angular-ui/getting-started/#toc-adding-the-styles).

- The Grid template directives are not working as we have change the prefix in order to prevent collisions between packages. (this will be done incrementally in the following days/weeks to rest of the components)

The prefix of all template directives selector has been changed to `kendoGrid` instead of just `kendo` as before. For example:

Before:
```html
<template kendoDetailTemplate let-dataItem>
   <category-details [category]="dataItem"></category-details>
</template>
```
After:
```html
<template kendoGridDetailTemplate let-dataItem>
   <category-details [category]="dataItem"></category-details>
</template>
```
We have uploaded a newer version documentation which showcase this. http://www.telerik.com/kendo-angular-ui/components/grid/

**Comment by sukhjeet81** [comment]
@rkonstantinov 
Hello, need help in the DetailTemplateDirective Kendo UI grid,
Is it possible to remove the + Sign which is on the 1st row for expanding row, i am able to expand Detail template on button click, but i need to remove + sign.
Please help me out in this.

**Comment by rkonstantinov** [comment]
@sukhjeet81, This repository is for submitting bugs with the components. 
Please open a [support ticket](https://www.telerik.com/account/support-tickets) via the official support system.

**Comment by sukhjeet81** [comment]
@rkonstantinov  I amd not able to rasie ticket in your system...:-(
