### ISSUE TITLE
Virtual scrolling triggers lots of refreshes when scrolling

### ISSUE THREAD

**Issue by sigVince** [telerik/kendo-angular2#199]
When virtual scrolling a grid with huge amounts of data, Grid will trigger lots of refreshes. Would be great to refresh only when scrolling is over, or add a debounce.
We are working with 100.000+ rows, and this is triggering lots of webservice calls thus lots of database queries. I've tried cancelling the previous request when a new one is triggered, but it's still a lot of requests gone to the server. I guess I could try debouncing it on my side, but I think it should be managed by the Grid component.
![vscroll](https://cloud.githubusercontent.com/assets/21171877/22113902/16467770-de68-11e6-96c5-b36ecdd93802.png)

Or actually, is there a way maybe with an other scroll mode to have the scrollbar cover only  the downloaded elements, and add more when I scroll all the way down, while keeping the first elements displayed? Like in a facebook/twitter feed, typically.

**Comment by tsvetomir** [comment]
We used to do debounce scrolling before, but decided against it in [later versions](http://www.telerik.com/kendo-angular-ui/components/grid/changelog/#toc-0121-2017-01-12).

@rkonstantinov can correct me, but I think the reason was that it created unacceptable lags when working with local data. You can still debounce the pageChange event to the desired rate. This is pretty straight-forward as [EventEmitters](https://angular.io/docs/ts/latest/api/core/index/EventEmitter-class.html) are Subjects. See [this snippet](http://plnkr.co/edit/MFAL4rE7obJ4xHX7n2zs?p=preview) for an example. We'll it to the docs as well.

**Comment by rkonstantinov** [comment]
Indeed that is correct. We decided that it is up to the consumer to decide if the debounce is required, providing more control based on the scenario at hand.

**Comment by sigVince** [comment]
You can close this btw.

In the end we're not going to use virtual scrolling anyway. Classic pagination for now. What we could use is infinite scrolling (facebook-like), is something like this planned in the future of kendo-angular, or shall we work on a custom solution?

**Comment by tsvetomir** [comment]
This is my observation with virtual scrolling as well - it's cool for demos, but its usability leaves a lot to be desired. 

Please, file a request for endless scrolling on our [UserVoice portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback) if you have minute.
This will help us gauge the overall interest and prioritize.

**Comment by sigVince** [comment]
Thanks, I've done so. Would be a great feature, and probably quick to dev given it's close to virtual scrolling in behavior.
