### ISSUE TITLE
Which npm package has Calendar and Date controls for Angular 2 Kendo RC?

### ISSUE THREAD

**Issue by pmangat** [telerik/kendo-angular2#200]

**Comment by tsvetomir** [comment]
This would be the `kendo-angular-date-inputs` package, but it's not published yet. We expect to have the first version out in a few days.

**Comment by gyoshev** [comment]
The `kendo-angular-dateinputs` package has been published. At this time the [Calendar component](http://www.telerik.com/kendo-angular-ui/components/dateinputs/calendar/) is available. We are working towards the release of the DatePicker and DateInput components -- until they are ready, the [following plunkr](http://plnkr.co/edit/B68ZymlS2S4VoOV8GLr7?p=preview) shows how to use the Calendar in a popup to achieve a basic date picker.

**Comment by pmangat** [comment]
Thank you!

**Comment by pkoecker** [comment]
Any update when the date inputs will be released?

**Comment by MurrayEaton** [comment]
The Datepicker has been released (http://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/) but the UX is terrible! How do I select a year, decade or century? 

Try selecting 2/1/1941

**Comment by yordanov** [comment]
@MurrayEaton
 
We believe this UI provides one of the fastest (if not the fastest) way in terms of interactions for selecting a date in the most common scenarios.

Here is a simple test:

Select the same date (today) for the next or previous year. E.g. August 8, 2018

With **[Kendo UI for jQuery DatePicker](http://demos.telerik.com/kendo-ui/datepicker/index)** and majority of datepickers available:
1.	Click on **`August 2017`** in the header – opens Year View
2.	Click on **`2017`** in the header – opens Decade View
3.	Click on **`2018`**
4.	Click on **`Aug`**
5.	Click on the day **`8`** to select

With **[Kendo UI for Angular DatePicker](http://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/)**:
1.	Scroll down to **`Aug`** 2018 (clicking on the month is optional)
2.	Click on the day **`8`** to select

However, we do agree that selecting a distant date e.g. someone’s birthday, requires a bit more scrolling with the current basic navigation setup. In addition, one cannot select e.g. a month only (as in “November, 2017” date format). To address these issues, we are considering the introduction of additional views for even faster navigation within a wider date range. You can vote for and follow [this idea in UserVoice](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/18990187-calendar-picker-component-fast-navigation).

**Comment by MurrayEaton** [comment]
We are using the Kendo controls however are looking at **other third party** calendar controls for this very issue. We have data entry forms for Patents filed in the early 1900's so scrolling is not an option for our users.

Telerik/Progress have been making calendar controls for years with a great experience. I dont know why you degraded the user experience other than to get something out quickly?

**Comment by yordanov** [comment]
Thank you for the feedback. We understand that we need to provide means to easily pick such date values while at the same time cover all other common scenarios with the least number of interactions possible. To have a better understanding of what we are aiming to ship by saying "additional views", please review the image below that depicts how a "Year view" will look like in the Calendar:

![calendar-year-view](https://user-images.githubusercontent.com/1118895/29078565-6c793134-7c63-11e7-96c4-db9748223a5d.png)


It basically covers the functionality present in the Kendo UI for jQuery Calendar/DatePicker + the additional side navigation that greatly enhances the experience, especially on mobile or when the end user's mouse or device supports kinetic scrolling.

We will appreciate, if you can share your thoughts on this so that we know we are on the right direction.

**Comment by MurrayEaton** [comment]
Its on the right path, but from a UX perspective I'm not sure about the reliance on the scroll wheel instead of a click?

The older bootstrap datepicker (https://angular-ui.github.io/bootstrap/#!#datepickerPopup) allowed for click navigation that was touch friendly and also included decade navigation (much like your jquery control). However picking years was a little difficult as the UI only showed the last 2 digits (**17**)

Anyway, your proposal seems valid and I will feel more comfortable once I can interact with it. Do you have a date on when it would be released so I can decide if we need to continue pursuing other libraries?

**Comment by MurrayEaton** [comment]
And I want to say thank you Yordanov for your quick and thorough response!

**Comment by crunchfactory** [comment]
If we're clicking on the 'Month, Year title' to get to the 'year', which, ok, is a _small step in the right direction_, why not also make the 'Year' title additionally clickable so one could then see the years (and eventually decades, etc..) by hero drill-down? One could still utilize the left menu, sure - it's nifty, but seriously, our Business AND QA/Testing are going to be less than pleased with us if they see this - "snazzy but big-picture usability is gone?!?!"

We need consistency. :)

**Comment by yordanov** [comment]
Thank you @MurrayEaton . The task is of high priority and we will do our best to have different views implemented by the end of September, right after the R3 official release.

@crunchfactory - That is exactly what I mean by saying “we are considering the introduction of additional views”. 

Regarding the “nifty” side navigation bar – we actually introduced it with the purpose to separate `navigation` from `selection`. With this implementation one uses the side menu to **navigate** and the Calendar to **select** a date. With the Kendo UI for jQuery implementation one uses **selection to navigate**, which is not OK from a UX perspective (e.g. one has to select a year in order to see the months, and then select a month in order to see the days… and the initial selection is lost…). 

We even tested how things would look like if we introduced steps, so that one can configure the navigation items with respect to the specific use case, but decided to ditch this approach as it is heavy implementation & configuration-wise:

![steps](https://user-images.githubusercontent.com/1118895/29112674-42b31a9c-7cf7-11e7-9a9e-3852e135897b.png)

**Comment by surya-gadiraju** [comment]
hello @yordanov do you have any update on year and month selection as mentioned above? Is that still on your radar.

**Comment by tsvetomir** [comment]
This feature is being actively developed. We'll follow up with preview releases in the [development channel](http://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) in a few weeks.

**Comment by kirhhof** [comment]
Hello kendo team,
Can one help me with the multiple dates selection like it was in silverlight and javascript versions?

**Comment by ggkrustev** [comment]
Hi @kirhhof,
currently the Calendar component for Angular doesn't support multiple cell selection. It is in our TODO list, but I won't be able to provide any time frame whether it will be available. I would suggest you follow our roadmap for updates.
