### ISSUE TITLE
Grid widget could support more events

### ISSUE THREAD

**Issue by oughton** [telerik/kendo-angular2#21]
Additional mouse events would be useful for the grid widget. Those are useful for implementing custom tool tips, context menus etc. Some examples might be,

- Right click event on rows/cells.
- Hover/unhover events on row/cells.
- Hover/unhover events on header cells.

**Comment by rusev** [comment]
We restrain from having events such as `mouse over/ mouse out` as they are known for the [performance penalties](http://stackoverflow.com/questions/12598481/html-dom-events) caused by them.

Have in mind that attaching DOM events will perform change detection by default. See this [blog post](http://blog.thoughtram.io/angular/2016/02/01/zones-in-angular-2.html#running-code-outside-angulars-zone) for more details. This is another reason why we don't want to add such events at this stage.

Such scenarios can be handled in the component consuming the `Grid`. A quick example for right click handling is available here: http://plnkr.co/edit/J6s2JByKkPOEnCJaeLB2?p=preview

**Comment by oughton** [comment]
Okay @rusev , that sounds reasonable. Thanks.
