### ISSUE TITLE
Why is the Sortable element stopping the propagation of the drag events?

### ISSUE THREAD

**Issue by maximedupre** [telerik/kendo-angular2#33]
This means that any drag and drop operation on a children component that necessitates the mouse position coordinates (`e.clientX`) won't work in Firefox. In order to get the mouse position during a drag event in Firefox, you need to listen to the `document`'s `dragover` event and get the data from there, as a drag event on any other element than the `document` in Firefox returns `e.clientX` to 0.

Is it required to stop the propagation of the drag events?

**Comment by Xizario** [comment]
@maximedupre, 

If you have nested components, that are both draggable, you will not want to drag them at the same time. Check out this plnkr:
http://plnkr.co/edit/Pw30m9j281mzlyEtetI7?p=preview
Here you have nested Sortable, if the event propagation is not stopped, after you start to drag the "Green" element into "Palette A" you will end up with reordered palettes, because the drag events will be handled by both inner and outer Sortable components.

The component does not rely on clientX/clientY information from the drag event, thus eliminating the calculations, making it possible to sort various of different sized content inside it and it works correctly in Firefox when nested.

From my perspective, accessing the document from the component is not good practice. And I hope they fix the Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=505521

If you want to cancel the propagation of the event, in order to bubble it to the document and handle it from inner control, I assume we could make this optional configuration with arrangement that if this option is set, nesting Sortables should be more carefully handled (using some events that we plan to introduce). 

If you have another suggestions it will be great to share them with us.

**Comment by maximedupre** [comment]
@Xizario

Right. It would be a very good idea to add a config to allow the drag events to bubble up, as I don't have nested Sortables and my use case necessitates having access to `clientX`.

Or there could be a boolean option named `nested`. When set to true, it stops the propagation. The advantage is that there only needs to be an `if` in the code, but the disadvantage is that a little bit of the logic for nested Sortables is left to the dev.

Of course, this Firefox bug is the root cause of the problem, but I don't think it will be fixed anytime soon as Firefox refuses to do so since 2009. While it is a bad practice to access the document inside a component, it's the only workaround.

Hopefully this will be fixed sooner than later, as I have to use a different library for DnD for now. I would like to use all Kendo components.

Thanks!

**Comment by Xizario** [comment]
After some changes in the internal logic, the stopPropagation could be safely removed from dragover and touchmove event handlers.
No modifications will be required in the example above, and it should continue to work the same way. 
The fix be part 0.4.0 version, because it is dependent on some other some other improvements.

I will close this issue once we publish the version that includes the fix.

**Comment by maximedupre** [comment]
Perfect! Thanks.
