### ISSUE TITLE
Kendo UI Grid - Row Detail + Scrolling bug

### ISSUE THREAD

**Issue by PierLucSimard** [telerik/kendo-angular2#35]
See this example
http://plnkr.co/edit/v5JpVghrstxNUTNzIz2I?p=preview

If u open detail of the row and scroll it does not work. In my application The rows ger render correctly but the detail does not change. Does Telerik give a discount/free licence on kendo UI for angular 2 for beta testers that provide alot of feeback?

**Comment by rkonstantinov** [comment]
I'm afraid that the grid component in the sample does not seem to be configured correctly. The skip option binding is missing. Also in order to use virtual scrolling and detail row, the [detailRowHeight](http://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#detailrowheight-number) option should be set. Also you should verify the the rowHeight is set to the actual value of the row height.

**Comment by PierLucSimard** [comment]
Thats right, after adding skip and detailRowHeight everythings seems to be working.

**Comment by Rohit221990** [comment]
If you are using a kendo grid with nested kendo grid in each row and scrolling virtual.(using angular 5)
case 1: After expand the and scroll the skip take last count.

sol: use  [detailRowHeight] = "36" in parent grid
