### ISSUE TITLE
Kendo Datasource

### ISSUE THREAD

**Issue by HJoost** [telerik/kendo-angular2#45]
Hi,

is it planned to implement Kendo Datasources like in the Kendo UI version, especially to support Odata-V4? If so, when to expect it?

Best Regards

Helmut

**Comment by rkonstantinov** [comment]
I'm afraid that we do not plan to have a DataSource component. We believe that having a DataSource like the one in Kendo UI for jQuery does not fit in the NG2 context. The framework already provides most of the DataSource functionality such as ability to fetch data, change tracking etc. Also there are pleiad of libraries and patterns for working with data. Thus, having single component to handle all of those seems more of a unnecessary constraint. 

However, we do plan to make available helper functions in order to streamline the Grid data operation descriptors serialization and operation handling. Providing better flexibility and integration with the rest of the NG2 ecosystem. Some functions already exist for [sorting and paging for OData](http://www.telerik.com/kendo-angular-ui/components/grid/data-binding/). As well as generating a comparer function for in-memory processing (this is demonstrated in [this sample](http://www.telerik.com/kendo-angular-ui/components/grid/#sorting)).

**Comment by ChrisProlls** [comment]
Kendo UI for jQuery allows the Grid to enable server paging, so we could use REST APIs to fetch the datas. It is possible for the moment with this version ? If not, will it be available in next releases ?

**Comment by HolgerPersch** [comment]
Yes, it's possible. But you will have to do it programatically like shown in the documentation's "[Paging](http://www.telerik.com/kendo-angular-ui/components/grid/#paging)" section.

**Comment by HJoost** [comment]
And what about the Autocomplete Feature with OData? If you have a lot of data, it's to much overhead to load all entries at first.

Next point are the grid filters with server side filtering. So you have to build your own logic to build the odata url's?

**Comment by rkonstantinov** [comment]
As I have mentioned we will provide functions to help serializing the filter/sort/group descriptors in OData URI format specification. But the developer will be responsible to make the request to the server and fetch the data.
