### ISSUE TITLE
Upload (R & D)

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-angular2#7]
We should check if Angular 2 does not do something specific when it comes to file uploads. If not - can we define the initial feature set? Please notice that this is not part of our initial preview milestone, unless something changes.

**Comment by tsvetomir** [comment]
Feature list a.k.a. spec

- Asynchronous uploads
- Templated file list
- Detachable drop zone
- Built-in validation rules for file size, extensions
- Localizable messages
- Events for selection, removal, progress, success and failure

Some important differences for customers coming from Kendo UI for jQuery:
- Synchronous uploads as they don't make sense in a SPA application
- Browser support will be limited to IE10+ and all modern browsers

  This is due to the removal of the legacy "upload-via-iframe" mode. It is very unreliable due to CORS limitations and it's replaced by the File API. 
- End-points are no longer required to return specially formulated responses

@Raisolution can chime in with code samples and implementation specifics.

**Comment by underlog** [comment]
Done - http://www.telerik.com/kendo-angular-ui/components/upload/
