### ISSUE TITLE
DropDownList complex (object) values never empty/invalid

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular2#79]
Hi,

when using the DropDownList component with complex values the selected defaultValue or any other value that should be considered empty (has empty value property) is not, which makes the `required` property irrelevant and requires custom logic for form validation.

Using kendo-angular-dropdowns@0.16.5:

### Example:
```typescript
@Component({
  selector: 'my-app',
  template: `
    <form>
            <kendo-dropdownlist
                [defaultItem]="defaultItem"
                [data]="genders"
                [textField]="'text'"
                [valueField]="'value'"
                [(ngModel)]="selectedGender"
                required
            ></kendo-dropdownlist>
        </label>
    </form>
  `
})
export class AppComponent {
    // This should make the form and field invalid but it does not
    defaultItem = { text: "Select your gender", value: null };
  
    public genders: Array<{ text: string, value: number }> = [
        { text: "Malе", value: 1 },
        { text: "Female", value: 2 }
    ];

    public selectedGender;
}
```

### Plunker:
http://plnkr.co/edit/ncamhxuX8T4TwN6FUESb?p=preview

**Comment by valchev** [comment]
@moxival Thank you for the bug report. We will fix the issue in a short period of time, most probably next week.

**Comment by valchev** [comment]
@moxival after further investigation, it seems that the build-in required validator does not support object validation. For reference see:

https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/validators.ts#L64
https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/validators.ts#L17

In order to resolve the scenario you should implement custom validation. We will update the examples in the documentation to demonstrate this, but we cannot provide a build-in solution.
